// One-click sample datasets — real messy lists so the wow moment lands
// without the user hunting for input. Each is intentionally unsorted.

export const SAMPLES = {
  'Mixed to-dos': [
    'Book flights for the Lisbon trip',
    'Reply to the landlord about the lease renewal',
    'Renew passport before it expires',
    'Buy oat milk and coffee beans',
    'Fix the leaking kitchen tap',
    'Schedule dentist cleaning',
    'Draft Q3 roadmap for the team',
    'Pay the electricity bill',
    'Pack sunscreen and adapters for Portugal',
    'Reserve a rental car in Porto',
    'Call the plumber about the radiator',
    'Order more printer paper',
    'Prepare slides for Monday standup',
    'Get travel insurance quote',
    'Return the library books',
    'Review the pull request from Sam',
    'Set up 1:1s with new hires',
    'Defrost the freezer this weekend',
    'Find a birthday gift for Mom',
    'Update the team wiki with the new process',
  ],
  'Product feedback': [
    'The app crashes when I upload a large file',
    'Love the new dark mode, easy on the eyes',
    'Export to CSV is missing some columns',
    'Onboarding took way too long, too many steps',
    'Search is really fast now, great job',
    'I can\'t find where to change my password',
    'The mobile layout breaks on my phone',
    'Wish there was a keyboard shortcut for save',
    'Billing page shows the wrong currency',
    'Dark mode is fantastic, please keep it',
    'App freezes when exporting big reports',
    'Login with Google keeps failing',
    'The new dashboard is beautiful and clear',
    'Notifications never arrive on time',
    'Password reset email took an hour to arrive',
    'Loading spinner runs forever on slow wifi',
    'CSV export drops the date column',
    'Really smooth and responsive overall',
    'Can you add a way to bulk-delete items',
    'The signup flow is confusing and long',
  ],
  'Research bookmarks': [
    'Attention is all you need — transformer paper',
    'How sourdough starters actually work',
    'A visual guide to CSS grid layout',
    'The economics of second-hand book markets',
    'Diffusion models explained from scratch',
    'Best espresso grind size for a moka pot',
    'Understanding TCP congestion control',
    'History of the Dewey decimal system',
    'Fine-tuning small language models cheaply',
    'Fermentation basics for home cooks',
    'Flexbox vs grid: when to use which',
    'Why used textbooks lose value so fast',
    'Vector databases and nearest-neighbor search',
    'Pour-over coffee ratios that work',
    'How DNS resolution actually happens',
    'Cataloguing a home library with ISBNs',
  ],
}

export const SAMPLE_NAMES = Object.keys(SAMPLES)
